### ISSUE TITLE
I keep getting these results.

### ISSUE THREAD

**Issue by SDRausty** [RalfWerner/integrated-process#3]
I keep getting these results:

`$ ~/buildAPKs/build.github.bash https://github.com/twaik`
`Writing 4 built APKs found to /data/data/com.termux/files/home/buildAPKs/sources/github/users/twaik/var/conf/NAPKS.db`                                                         `Processing ~/buildAPKs/var/db/BNAMES: Replacing twaik 20200111 27450755 761 9 4  in ~/buildAPKs/var/db/BNAMES: Adding BNAMES to /data/data/com.termux/files/home/buildAPKs/sources/github/users/twaik/var/conf/NAMES.db  DONE`                                         
AND 
                                                                                    `$ ~/buildAPKs/build.github.bash https://github.com/termux`
`Writing 4 built APKs found to /data/data/com.termux/files/home/buildAPKs/sources/github/orgs/termux/var/conf/NAPKS.db`                                                         `Processing ~/buildAPKs/var/db/log/BNAMESNAPKs: Replacing termux 20200111 21668790 765 13 4  in ~/buildAPKs/var/db/log/BNAMESNAPKs: Adding log/BNAMESNAPKs to /data/data/com.termux/files/home/buildAPKs/sources/github/orgs/termux/var/conf/NAMES.db  DONE`

In veiw of the fact that:
```
$ l ~/storage/downloads/builtAPKs/github.orgs.termux.20200111/
total 18064
drwxrwx---  2 root     4096 Jan 11 07:18 .
drwxrwx--- 10 root     4096 Jan 11 07:28 ..
-rw-rw----  1 root    17185 Jan 11 07:18 com.example.termuxam.1578745107.apk
-rw-rw----  1 root    28750 Jan 11 07:15 com.termux.failsafe.1578744942.apk
-rw-rw----  1 root 18394991 Jan 11 07:17 com.termux.styling.1578744981.apk
-rw-rw----  1 root    36690 Jan 11 07:15 com.termux.terminal.1578744849.apk
```
AND
```
$ l ~/storage/downloads/builtAPKs/github.users.twaik.20200111/
total 264
drwxrwx---  2 root  4096 Jan 11 07:00 .
drwxrwx--- 10 root  4096 Jan 11 07:28 ..
-rw-rw----  1 root 23060 Jan 11 06:17 com.example.SanAngeles.1578741469.apk
-rw-rw----  1 root 23065 Jan 11 06:58 com.example.SanAngeles.1578743902.apk
-rw-rw----  1 root  4292 Jan 11 06:18 com.sion.sparkle.1578741479.apk
-rw-rw----  1 root  4293 Jan 11 06:58 com.sion.sparkle.1578743913.apk
-rw-rw----  1 root 36327 Jan 11 06:18 com.termux.terminal.1578741497.apk
-rw-rw----  1 root 36328 Jan 11 06:59 com.termux.terminal.1578743952.apk
-rw-rw----  1 root 60902 Jan 11 06:19 org.x.android.1578741584.apk
-rw-rw----  1 root 60897 Jan 11 07:00 org.x.android.1578744028.apk
```
AND 

[![Screenshot_20200108-222645.png](https://raw.githubusercontent.com/BuildAPKs/docsBuildAPKs/master/bitpics/screenshots/Screenshot_20200108-222645.png)](https://buildapks.github.io/docsBuildAPKs/init)

Reference: https://github.com/twaik/xorg-bionic-android/issues/2 Are better results possible? 

Cross references: 
* https://github.com/termux/termux-x11/issues/8
* https://github.com/twaik/termux-x11/issues/6

> Are better results possible? 

Can the gradle dependencies be trimmed from the source code of these project?

**Comment by RalfWerner** [comment]
I close here because duplicates already exist and _Xorg_ has died.

**Comment by SDRausty** [comment]
> and Xorg has died.

> It does not work because you have missed one thing.
You need to compile stuff under https://github.com/termux/termux-x11/tree/master/app/src/main/jni.
Otherwise application will not work.

update from: https://gitter.im/termux/termux

Xorg might not be dead
